version: '3'

networks:
  default: {}

services:
  redis:
    image: redis:3.2
  smtp:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

  # The Database
  mysql:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    container_name: thd_mysql_con
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_RANDOM_ROOT_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: root_password

  project:
    container_name: project
    build:
      context: ./project
    working_dir: /var/www/html/project_laravel
    volumes:
      - ${PROJECT_PATH}:/var/www/html/project_laravel
      - ./project/apache/logs:/var/log/httpd
    ports:
      - 7000:80
    links:
      - mysql
    depends_on:
      - mysql
    env_file: .env

volumes:
  dbdata:
